telegram:
  bot:
#    не вписывайте данные, так как можете отправить в публичный репозиторий
#    используйте переменные среды для установки значений
    username: ParvumBot
    token: 7304795454:AAGW8R4Vx9UjDKEiudakT9TS_4yZdFZ0kGA
    notify:
      delay:
        value: 10
        unit: MINUTES

binance:
  api:
    getPrice: https://api.binance.com/api/v3/avgPrice?symbol=BTCUSDT

db:
  driver:
    name: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/db
  user: root
  password: root
